server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: 'jdbc:postgresql://localhost:5432/product-service'
    username: postgres
    password: _one_look1
    driver-class-name: org.postgresql.Driver
  application:
    name: PRODUCT-SERVICE
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

openapi:
  service:
    title: order-service doc
    version: 1.0.0
    url: http://localhost:9191 #api gateway url
springdoc:
  api-docs:
    path: /product-service/v3/api-docs
  swagger-ui:
    path: /product-service/swagger-ui.html